#!/usr/bin/env python3
"""Generate and validate the native Nucleus render SDK build contract.

The SDK is generated by Nucleus and consumed read-only by Noctalia.  This tool
is intentionally usable from both repositories: Nucleus invokes ``generate``
while staging an SDK; Meson invokes ``validate`` before it compiles Noctalia.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import pathlib
import re
import subprocess
import sys
from typing import Any


SCHEMA_VERSION = 1
FEATURE_DEFINES = [
    "NDEBUG",
    "SK_GRAPHITE",
    "SK_DAWN",
    "SK_VULKAN",
    "SK_GAMMA_APPLY_TO_A8",
    "SK_ALLOW_STATIC_GLOBAL_INITIALIZERS=1",
]
LINK_GROUP = [
    "skia",
    "skshaper",
    "skparagraph",
    "skunicode_core",
    "skunicode_icu",
    "svg",
    "skcms",
    "skresources",
    "freetype2",
    "harfbuzz",
    "icu",
    "png",
    "jpeg",
    "jpeg12",
    "jpeg16",
    "webp",
    "webp_sse41",
    "expat",
    "zlib",
    "wuffs",
    "dng_sdk",
    "piex",
    "dawn_combined",
]
SYSTEM_LIBRARIES = ["vulkan", "fontconfig", "freetype", "z", "dl", "pthread", "m"]
REQUIRED_GN_ARGUMENTS = {
    "is_official_build": "true",
    "skia_enable_tools": "false",
    "skia_enable_graphite": "true",
    "skia_use_partition_alloc": "false",
    "skia_use_dawn": "true",
    "skia_use_vulkan": "true",
    "dawn_enable_vulkan": "true",
    "skia_use_freetype": "true",
    "skia_use_harfbuzz": "true",
    "skia_use_icu": "true",
    "skia_use_fontconfig": "true",
    "skia_enable_skparagraph": "true",
    "skia_enable_skunicode": "true",
    "skia_enable_svg": "true",
}


class ContractError(RuntimeError):
    pass


def run(argv: list[str], *, input_text: str | None = None) -> str:
    try:
        proc = subprocess.run(
            argv,
            input=input_text,
            text=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            check=True,
        )
    except (OSError, subprocess.CalledProcessError) as error:
        detail = getattr(error, "stderr", "") or str(error)
        raise ContractError(f"command failed: {' '.join(argv)}: {detail.strip()}") from error
    return proc.stdout.strip()


def sha256(path: pathlib.Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for chunk in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def compiler_identity(compiler: str) -> dict[str, Any]:
    version_output = run([compiler, "--version"])
    first_line = version_output.splitlines()[0] if version_output else ""
    match = re.search(r"clang version\s+([^\s]+)", first_line)
    if not match:
        raise ContractError(f"Nucleus requires Clang; compiler reported: {first_line!r}")

    macros = run(
        [compiler, "-dM", "-E", "-x", "c++", "-include", "version", "-"],
        input_text="\n",
    )
    libcxx_match = re.search(r"^#define _LIBCPP_VERSION\s+(\d+)\s*$", macros, re.MULTILINE)
    if not libcxx_match:
        raise ContractError("Nucleus requires libc++; _LIBCPP_VERSION is not defined")

    return {
        "id": "clang",
        "version": match.group(1),
        "version_line": first_line,
        "target_triple": run([compiler, "-dumpmachine"]),
        "libcxx": {
            "version": int(libcxx_match.group(1)),
            "abi_namespace": "__1",
        },
    }


def sdk_paths(sdk: pathlib.Path) -> tuple[pathlib.Path, pathlib.Path, pathlib.Path]:
    skia = sdk / "include" / "skia"
    library_dir = sdk / "lib" / "skia-graphite"
    args_gn = library_dir / "args.gn"
    for path in (skia, library_dir, args_gn):
        if not path.exists():
            raise ContractError(f"render SDK is missing {path}")
    return skia, library_dir, args_gn


def parse_gn_args(path: pathlib.Path) -> dict[str, str]:
    result: dict[str, str] = {}
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.split("#", 1)[0].strip()
        if not line or "=" not in line:
            continue
        key, value = line.split("=", 1)
        result[key.strip()] = value.strip()
    return result


def validate_gn_contract(path: pathlib.Path) -> None:
    arguments = parse_gn_args(path)
    wrong = [
        f"{key}={arguments.get(key, '<missing>')} (expected {value})"
        for key, value in REQUIRED_GN_ARGUMENTS.items()
        if arguments.get(key) != value
    ]
    if wrong:
        raise ContractError("incompatible Skia GN contract: " + ", ".join(wrong))


def skia_revision(skia: pathlib.Path) -> str:
    revision_file = skia / "SKIA_REVISION"
    if revision_file.is_file():
        revision = revision_file.read_text(encoding="utf-8").strip()
        if revision:
            return revision
    try:
        return run(["git", "-C", str(skia), "rev-parse", "HEAD"])
    except ContractError as error:
        raise ContractError("SDK must contain include/skia/SKIA_REVISION or Skia Git metadata") from error


def archive_inventory(library_dir: pathlib.Path) -> list[dict[str, str]]:
    archives: list[dict[str, str]] = []
    for name in LINK_GROUP:
        archive = library_dir / f"lib{name}.a"
        if not archive.is_file():
            raise ContractError(f"render SDK is missing required archive {archive.name}")
        archives.append({"file": archive.name, "sha256": sha256(archive)})
    unexpected = sorted(
        path.name for path in library_dir.glob("*.a") if path.name not in {item["file"] for item in archives}
    )
    if unexpected:
        raise ContractError("render SDK archive inventory is not declared by Nucleus: " + ", ".join(unexpected))
    return archives


def generate(args: argparse.Namespace) -> None:
    sdk = pathlib.Path(args.sdk).resolve()
    skia, library_dir, args_gn = sdk_paths(sdk)
    validate_gn_contract(args_gn)
    manifest = {
        "schema_version": SCHEMA_VERSION,
        "sdk": "nucleus-render",
        "compiler": compiler_identity(args.compiler),
        "skia": {
            "commit": skia_revision(skia),
            "gn_args_sha256": sha256(args_gn),
            "feature_defines": FEATURE_DEFINES,
        },
        "archives": archive_inventory(library_dir),
        "link_contract": {
            "archive_group": LINK_GROUP,
            "system_libraries": SYSTEM_LIBRARIES,
        },
    }
    output = pathlib.Path(args.output) if args.output else sdk / "manifest.json"
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(output)


def require_equal(label: str, actual: Any, expected: Any) -> None:
    if actual != expected:
        raise ContractError(f"{label} mismatch: SDK has {expected!r}, compiler/build has {actual!r}")


def validate(args: argparse.Namespace) -> None:
    sdk = pathlib.Path(args.sdk).resolve()
    skia, library_dir, args_gn = sdk_paths(sdk)
    manifest_path = sdk / "manifest.json"
    if not manifest_path.is_file():
        raise ContractError(
            f"render SDK is unversioned: missing {manifest_path}; regenerate it with the Nucleus SDK tooling"
        )
    try:
        manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as error:
        raise ContractError(f"invalid render SDK manifest: {error}") from error

    require_equal("manifest schema", manifest.get("schema_version"), SCHEMA_VERSION)
    require_equal("SDK kind", manifest.get("sdk"), "nucleus-render")
    identity = compiler_identity(args.compiler)
    recorded_identity = manifest.get("compiler", {})
    for key in ("id", "version", "target_triple"):
        require_equal(f"compiler {key}", identity.get(key), recorded_identity.get(key))
    require_equal(
        "libc++ version",
        identity["libcxx"]["version"],
        recorded_identity.get("libcxx", {}).get("version"),
    )
    require_equal(
        "libc++ ABI namespace",
        identity["libcxx"]["abi_namespace"],
        recorded_identity.get("libcxx", {}).get("abi_namespace"),
    )

    validate_gn_contract(args_gn)
    recorded_skia = manifest.get("skia", {})
    require_equal("Skia revision", skia_revision(skia), recorded_skia.get("commit"))
    require_equal("Skia GN arguments", sha256(args_gn), recorded_skia.get("gn_args_sha256"))
    require_equal("Skia feature defines", FEATURE_DEFINES, recorded_skia.get("feature_defines"))
    require_equal("Skia archive group", LINK_GROUP, manifest.get("link_contract", {}).get("archive_group"))
    require_equal(
        "Skia system libraries", SYSTEM_LIBRARIES, manifest.get("link_contract", {}).get("system_libraries")
    )
    require_equal("Skia archive inventory", archive_inventory(library_dir), manifest.get("archives"))
    print(f"validated Nucleus render SDK: {sdk}")


def main() -> int:
    parser = argparse.ArgumentParser()
    subparsers = parser.add_subparsers(dest="action", required=True)
    for action in ("generate", "validate"):
        command = subparsers.add_parser(action)
        command.add_argument("--sdk", required=True)
        command.add_argument("--compiler", required=True)
        if action == "generate":
            command.add_argument("--output")
    args = parser.parse_args()
    try:
        (generate if args.action == "generate" else validate)(args)
    except ContractError as error:
        print(f"Nucleus render SDK error: {error}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
